### ISSUE TITLE
Availability of ShuttleSDK.dll?

### ISSUE THREAD

**Issue by Slixxor** [EddieMac74/ShuttleNET#2]
It seems like the project might work but the ShuttleSDK.dll file is missing, Where can this be found?

I've done a good search but it seems very difficult to find.

**Comment by EddieMac74** [comment]
Email me ***@***.***

**Comment by EddieMac74** [comment]
There are 2 versions of the dll file. ShuttleSDK.dll and ShuttleSDK64.dll. They are 32 bit and 64 bit respectively. My code is for the 32 bit version. You need to change the import signatures in my wrapper dll for the 64 bit version. 

If you have the Contour Shuttle drivers installed on your computer under Windows, both dll files can be found at:
  
C:\Program Files (x86)\Contour Shuttle\ShuttleSDK.dll

Make sure you also read the  License document Contour included in the same directory

**Comment by Slixxor** [comment]
Forgive me for being a bit green on this, I have installed the latest driver from the website. There is no ShuttleSDK.dll file found anywhere after install. 

I have had a user submit their file and I am indeed experiencing an issue with it. Specifically:

An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

I have tried setting the project to output as x64 and AnyCPU but have the same result. Is there something I am missing?

**Comment by Slixxor** [comment]
Yeah sorry man I can’t see the email. It’s blocked out.

 

Try mine; david at slixxor dot com

 

Cheers,

 

Dave

**Comment by Slixxor** [comment]
Ok so, I had the files submitted to me by a user. I have managed to now get past the architecture mismatch by using the ShutlteSDK64.dll file.

I have subsequently now reached the next step in the chain. :)

Here is the code changes I've, made:

`      [DllImport("ShuttleSDK64.dll", CallingConvention = CallingConvention.StdCall, EntryPoint = "_Shuttle_Register_Callback_Global@12")]
        private static extern uint _Shuttle_RegisterCallback_Global_Msg(MulticastDelegate shuttleproc, ushort type, ushort devno);

        [DllImport("ShuttleSDK64.dll", CallingConvention = CallingConvention.StdCall, EntryPoint = "_Shuttle_Register_Callback@12")]
        private static extern uint _Shuttle_RegisterCallback_Msg(MulticastDelegate shuttleproc, ushort type, ushort devno);

        [DllImport("ShuttleSDK64.dll", CallingConvention = CallingConvention.StdCall, EntryPoint = "_Shuttle_Unregister_Callback@8")]
        private static extern int _Shuttle_UnregisterCallback_Msg(ushort type, ushort devno);`

Here is the new exception:

![image](https://github.com/EddieMac74/ShuttleNET/assets/7635880/c2748db9-6b7f-4874-8155-0f66efdd4cb5)

I feel like maybe the entry ID is wrong but this is the first time I've had to actually "COM" anything to this level. :)

Shout out if you may have a solution. The next step is to actually get it to tie in with everything else. :)

**Comment by EddieMac74** [comment]
Hey sorry for the late reply. Been busy at work.

The version of the dll code you are working with is for 32 bit machines.
That's why it is not working. The error us telling you as much.

You need to have the signatures for each imports modified to match the
signature for the 64 bit dll.

I am working now to create a 64 bit version of the code right now. I will
see if I can get it finished and uploaded tonight. If so I will send you
the link to the new code.

Also, what are you creating with the code ?

Thanks,

Eddie

**Comment by EddieMac74** [comment]
Hey, I changed the code on GitHub to reflect the ability to use either the
32 bit ShuttleSDK.dll or thebShuttleSDK64.dll

Comment out the 32 bit code and uncomment the 64 bit code.

Make sure you specify then proper processor type to target when compiling
the code.

Thanks,

Eddie

**Comment by EddieMac74** [comment]
Almost forgot...the new code is in the ShuttleNet/Wrapper.cs file

**Comment by Slixxor** [comment]
oh man, I already figured it out about a hour ago for the X64 version. I used Dependency Walker to track down the entry points. 

This should work for you:


```
        [DllImport("ShuttleSDK64.dll", CallingConvention = CallingConvention.StdCall, EntryPoint = "Shuttle_Register_Callback_Global")]
        private static extern uint _Shuttle_RegisterCallback_Global_Msg(MulticastDelegate shuttleproc, ushort type, ushort devno);

        [DllImport("ShuttleSDK64.dll", CallingConvention = CallingConvention.StdCall, EntryPoint = "Shuttle_Register_Callback")]
        private static extern uint _Shuttle_RegisterCallback_Msg(MulticastDelegate shuttleproc, ushort type, ushort devno);

        [DllImport("ShuttleSDK64.dll", CallingConvention = CallingConvention.StdCall, EntryPoint = "Shuttle_Unregister_Callback")]
        private static extern int _Shuttle_UnregisterCallback_Msg(ushort type, ushort devno);

        private delegate void ShuttleCallback(uint @event, byte status, ushort type, ushort devno);

        private static ShuttleCallback callback;
```

**Comment by EddieMac74** [comment]
Sweet. What are you building ?

**Comment by Slixxor** [comment]
I have CNC control software and a few users have requested Shuttle jogging support. I don't physically have a unit so testing is.. well, fun.

**Comment by Slixxor** [comment]
All resolved, all works, thanks for your help legend!

**Comment by EddieMac74** [comment]
This is a really great application for the shuttle. I am designing my own
device and hopefully can so ebay put it on kick starter. I would be very
interested to have your input on what would make a great shuttle / job
device.

**Comment by Slixxor** [comment]
What a great question. Here is a side by side comparison of a pro pendant I've added support for and the shuttle. Credit to you in the video description. :)https://youtu.be/NiZIQbVs_a4Get Outlook for Android

**Comment by Slixxor** [comment]
If you do make a pendant, I might be keen to stock it. :)

**Comment by EddieMac74** [comment]
Excellent. I have ordered the electronic components to start the prototype.
